services:
  - type: web
    name: orange-money-paiement
    env: python
    region: ohio  # ou frankfurt, singapore selon votre localisation
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: CHECK_INTERVAL_MINUTES
        value: "14"
    disk:
      name: paiements-data
      mountPath: /opt/render/project/src
      sizeGB: 1
    healthCheckPath: /health
    autoDeploy: true